### ISSUE TITLE
Lesson 2 - Persistence failure when replaying events for persistenceId

### ISSUE THREAD

**Issue by sthomas1978** [petabridge/akkadotnet-cluster-workshop#972]
Hi

I am trying to complete lesson 2 of the tutorial and I have read and re-read the tutorial to see what I am doing wrong but cannot spot the mistake.

Everytime I bring up the service stack and look at the logs for the tradeprocessor service I see the following error message

src-tradeprocessor-1  | [ERROR][10/05/2022 07:36:42][Thread 0042][akka.tcp://AkkaTrader@9951bfd18690:5110/user/orderbooks/APPL] Persistence failure when replaying events for persistenceId [APPL-orderBook]. Last known sequence number [0]src-tradeprocessor-1  | Cause: Akka.Pattern.OpenCircuitException: Circuit Breaker is open; calls are failing fast
src-tradeprocessor-1  |  ---> System.ArgumentNullException: Value cannot be null. (Parameter 'name')
src-tradeprocessor-1  |    at MongoDB.Driver.Core.Misc.Ensure.IsNotNullOrEmpty(String value, String paramName)
src-tradeprocessor-1  |    at MongoDB.Driver.MongoDatabaseImpl.GetCollection[TDocument](String name, MongoCollectionSettings settings)
src-tradeprocessor-1  |    at Akka.Persistence.MongoDb.Journal.MongoDbJournal.<PreStart>b__12_2()
src-tradeprocessor-1  |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
src-tradeprocessor-1  | --- End of stack trace from previous location where exception was thrown ---
src-tradeprocessor-1  |    at System.Lazy`1.CreateValue()
src-tradeprocessor-1  |    at Akka.Persistence.MongoDb.Journal.MongoDbJournal.ReadHighestSequenceNrAsync(String persistenceId, Int64 fromSequenceNr)
src-tradeprocessor-1  |    at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
src-tradeprocessor-1  |    at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
src-tradeprocessor-1  |    at Akka.Pattern.HalfOpen.Invoke[T](Func`1 body)
src-tradeprocessor-1  |    at Akka.Persistence.Journal.AsyncWriteJournal.<>c__DisplayClass19_0.<<HandleReplayMessages>g__ExecuteHighestSequenceNr|0>d.MoveNext()
src-tradeprocessor-1  |    --- End of inner exception stack trace ---

In the traders service I have following

src-traders-1  | [ERROR][10/05/2022 07:41:17][Thread 0069][akka.tcp://AkkaTrader@e4100dc4a6f7:5110/user/$rc] Error while waiting for SubscribeAck for [SAVE-Fill] - retrying in 5s.
src-traders-1  | Cause: Akka.Actor.AskTimeoutException: Timeout after 00:00:03 seconds
src-traders-1  |    at Akka.CQRS.Subscriptions.Actor.ActorTradeSubscriptionManager.Subscribe(String tickerSymbol, TradeEventType[] events, IActorRef subscriber) in C:\training\akka.net\cluster\src\Akka.CQRS.Subscriptions\Actor\ActorTradeSubscriptionManager.cs:line 22

Any help would be much appreciated

**Comment by mertigdir** [comment]
update Akka.CQRS.TradeProcessor.Service --> app.conf 


```
akka {
	actor {
		provider = cluster
	}
						
	remote {
		dot-netty.tcp {
				hostname = "127.0.0.1"
				port = 5055
			}
	}			

	cluster {
		#will inject this node as a self-seed node at run-time
		seed-nodes = ["akka.tcp://AkkaTrader@127.0.0.1:5055"] 
		roles = ["trade-processor" , "trade-events"]
	}

	persistence{
		journal {
		    plugin = "akka.persistence.journal.mongodb"
			mongodb.class = "Akka.Persistence.MongoDb.Journal.MongoDbJournal, Akka.Persistence.MongoDb"
			mongodb.collection = "EventJournal"
			mongodb.metadata-collection = "Metadata"
			mongodb.auto-initialize = "on"
			#mongodb.stored-as = binary
		}

		snapshot-store {
		    plugin = "akka.persistence.snapshot-store.mongodb"
			mongodb.class = "Akka.Persistence.MongoDb.Snapshot.MongoDbSnapshotStore, Akka.Persistence.MongoDb"
			mongodb.collection = "SnapshotStore"
			#mongodb.stored-as = binary
		}
	}
}
```

and Update common.props 

    <NBenchVersion>1.2.2</NBenchVersion>
    <XunitVersion>2.4.2</XunitVersion>
    <TestSdkVersion>17.2.0</TestSdkVersion>
    <AkkaVersion>1.5.1</AkkaVersion>
    <AkkaBootstrapVersion>0.5.3</AkkaBootstrapVersion>
    <AkkaPersistenceExtrasVersion>1.5.1</AkkaPersistenceExtrasVersion>
